ALTER TABLE pairs DROP CONSTRAINT IF EXISTS first_id_fk;
ALTER TABLE pairs ADD CONSTRAINT first_id_fk FOREIGN KEY (first_id) REFERENCES words ON DELETE CASCADE;
ALTER TABLE pairs DROP CONSTRAINT IF EXISTS second_id_fk;
ALTER TABLE pairs ADD CONSTRAINT second_id_fk FOREIGN KEY (second_id) REFERENCES words ON DELETE CASCADE;
ALTER TABLE replies DROP CONSTRAINT IF EXISTS word_id_fk;
ALTER TABLE replies ADD CONSTRAINT word_id_fk FOREIGN KEY (word_id) REFERENCES words ON DELETE CASCADE;