ALTER TABLE replies DROP CONSTRAINT IF EXISTS pair_id_fk;
ALTER TABLE replies ADD CONSTRAINT pair_id_fk FOREIGN KEY (pair_id) REFERENCES pairs ON DELETE CASCADE;

ALTER TABLE pairs DROP CONSTRAINT IF EXISTS chat_id_fk;
ALTER TABLE pairs ADD CONSTRAINT chat_id_fk FOREIGN KEY (chat_id) REFERENCES chats ON DELETE CASCADE;